name: Release Packages

on:
  workflow_dispatch: {}
  push:
    tags:
      - "v*.*.*"

jobs:
  publish-ts-sdk:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: "16.14.2"
          registry-url: https://npm.pkg.github.com/

      - name: Install dependencies
        run: yarn install

      - name: Build TS SDK
        run: yarn build-sdk

      - name: Publish npm package
        run: yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.HAMMYFLIP_PAT}}

  release-binaries:
    runs-on: ubuntu-latest
    name: Release verifiable binaries
    steps:
      - uses: actions/checkout@v2

      - name: Install anchor
        run: npm i -g @project-serum/anchor-cli@0.24.2

      - name: Build programs
        run: anchor build --verifiable

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/deploy/*
            target/idl/*
            target/verifiable/*